### ISSUE TITLE
Pre/post suite hooks in RCC Robots

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#111]
(Was: "Leverage Ansible Python API for pre/post suite hooks")

Setting up a client environment can require a lot of steps (pip install modules, yum/apt/chocolatey install 3rd party tools, setting environment variables for tests etc.). 
Perhaps also tasks are needed _after_ a suite has run.

It is good style that tasks necessary to create solid test conditions should always be part of the Robot suite itself. (`Suite Setup / Suite Teardown`).  
But there are probably tasks beyond this scope. A pre/post hook mechanism could supplement the toolset. 

The Robotmk runner can assist in some way that it searches for a `robotmk_playbook_pre.yml` file within the suite's dir and uses the Python API of Ansible to start this playbook. 
It gets started by default everytime the runner starts the Robot suite. 
Each time, the last execution date is stored within the suite's JSON state file. 
Execution control: 
* An optional numeric prefix (example: `86400_robotmk_playbook_pre.yml`) could configure the execution interval of the playbook to execute it only once a day. 
* If there is no numeric prefix, the playbook only gets executed the MD5 hash of the playbook file differs from the one stored within the suite state JSON file. 

The same could apply to the post hook playbook `robotmk_playbook_post.yml`.

**Comment by simonmeggle** [comment]
With RCC (planned in #148), the `robot.yaml` can contain tasks like `robotmk_prehook` and `robotmk_posthook`:

```
tasks:
  # install and prepare everyhting which is needed to execute the SUT on this machine
  robotmk_pre-hook:
    shell: ansible-playbook sut_preparation.yml
  # the e2e test itself
  robotmk:
    shell: python -m robot fooapp.robot --variable SUT_TYPE:PROD
  # do this after each test run
  robotmk_post-hook:
    shell: ansible-playbook sut_housekeeping.yml
```

The `conda.yaml` contains the installation instruction for ansible.

Each robot run will then be executed in an isolated environment and can take care for all preconditions needed on the target machine. 

Ansible and Robot seems to be a perfect combination here - this approach would keep away all the "dirty work" from Robot. Because, for configuration management Robot Framework is definitely not the best choice.
