### ISSUE TITLE
Problems with Robot suites directory in CheckMK 2.0.0p5 

### ISSUE THREAD

**Issue by kleinski** [simonmeggle/robotmk#127]
Using not a specified _Robot suites directory_ in the bakery leads to:

![1](https://user-images.githubusercontent.com/3239736/120306878-a3164b00-c2d2-11eb-99f9-11672d7bc0a7.png)

Having specified a _Robot suites directory_ in the bakery leads to:

![2](https://user-images.githubusercontent.com/3239736/120307059-d527ad00-c2d2-11eb-9822-635e6c680a0e.png)

Corresponding robotmk.yml:
```
global:
  execution_mode: agent_serial
  agent_output_encoding: zlib_codec
  transmit_html: true
  logging: true
  log_rotation: '14'
  robotdir:
    robotdir: C:\ProgramData\checkmk\agent\robot2
  cache_time: 960
  execution_interval: 900
suites: {}
```
