### ISSUE TITLE
Wrong formatting of variable argument

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#38]
Wrong: 
```
suites:
  sum_prices:
    name: Buchpreis Summe
    variables:
    - BOOKPRICE_SOLLWERT:500
```
Correct: 
```
suites:
  sum_prices:
    name: Buchpreis Summe
    variable:
      BOOKPRICE_SOLLWERT: 500

```
